# Generated by Django 6.0.7 on 2026-08-26 23:04

import common.models.base
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('type', models.CharField(choices=[('national', 'National Holiday'), ('company', 'Company Holiday (Summer/New Year, etc.)')], default='national', max_length=20, verbose_name='Holiday Type')),
                ('name', models.CharField(help_text="e.g., New Year's Day, Summer Vacation, Foundation Day", max_length=100, verbose_name='Holiday Name')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'db_table': 'holiday',
                'ordering': ('date',),
            },
            bases=(common.models.base.AuthorizedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostcodeImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=7, verbose_name='Postcode')),
                ('municipality_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Municipality Code')),
                ('town_name', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Town Name')),
                ('town_name_kana', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Town Name Kana')),
            ],
            options={
                'db_table': 'tmp_postcode_import',
            },
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Prefecture Code')),
                ('name', models.CharField(max_length=100, verbose_name='Prefecture Name')),
            ],
            options={
                'verbose_name': 'Prefecture',
                'verbose_name_plural': 'Prefectures',
                'db_table': 'prefecture',
                'ordering': ('code',),
            },
            bases=(common.models.base.AuthorizedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Work Pattern Name')),
                ('start_time', models.TimeField(blank=True, default='09:30', null=True, verbose_name='Standard Start Time')),
                ('end_time', models.TimeField(blank=True, default='18:00', null=True, verbose_name='Standard End Time')),
                ('standard_work_time', models.TimeField(blank=True, default='07:30', null=True, verbose_name='Standard Working Time')),
                ('half_day_time', models.TimeField(blank=True, default='12:30', null=True, verbose_name='Half Day Time')),
                ('lunch_break_start_time', models.TimeField(blank=True, default='12:00', null=True, verbose_name='Lunch Break Start Time')),
                ('lunch_break_end_time', models.TimeField(blank=True, default='13:00', null=True, verbose_name='Lunch Break End Time')),
                ('break1_start_time', models.TimeField(blank=True, default='18:00', null=True, verbose_name='Break 1 Start Time')),
                ('break1_end_time', models.TimeField(blank=True, default='18:30', null=True, verbose_name='Break 1 End Time')),
                ('break2_start_time', models.TimeField(blank=True, default='20:00', null=True, verbose_name='Break 2 Start Time')),
                ('break2_end_time', models.TimeField(blank=True, default='20:30', null=True, verbose_name='Break 2 End Time')),
                ('break3_start_time', models.TimeField(blank=True, default='22:30', null=True, verbose_name='Break 3 Start Time')),
                ('break3_end_time', models.TimeField(blank=True, default='22:45', null=True, verbose_name='Break 3 End Time')),
                ('break4_start_time', models.TimeField(blank=True, default='03:00', null=True, verbose_name='Break 4 Start Time')),
                ('break4_end_time', models.TimeField(blank=True, default='03:30', null=True, verbose_name='Break 4 End Time')),
                ('break5_start_time', models.TimeField(blank=True, default='09:00', null=True, verbose_name='Break 5 Start Time')),
                ('break5_end_time', models.TimeField(blank=True, default='09:30', null=True, verbose_name='Break 5 End Time')),
            ],
            options={
                'verbose_name': 'Work Pattern',
                'verbose_name_plural': 'Work Patterns',
                'db_table': 'work_pattern',
                'ordering': ('start_time',),
            },
            bases=(common.models.base.AuthorizedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_flag', models.BooleanField(default=True, verbose_name='Valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=150, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(max_length=150, verbose_name='Updated by')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Organization Code')),
                ('name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='common.organization', verbose_name='Parent Organization')),
                ('work_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.workpattern', verbose_name='Work Pattern')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organization',
            },
            bases=(common.models.base.AuthorizedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Municipality Code')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipality Name')),
                ('name_kana', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipality Name Kana')),
                ('prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.prefecture', verbose_name='Prefecture')),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
                'db_table': 'municipality',
                'ordering': ('code',),
            },
            bases=(common.models.base.AuthorizedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_flag', models.BooleanField(default=True, verbose_name='Valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=150, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(max_length=150, verbose_name='Updated by')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='Employee Number')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='common.organization', verbose_name='Belongs to')),
                ('work_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.workpattern', verbose_name='Work Pattern')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'member',
            },
            bases=(common.models.base.AuthorizedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=7, verbose_name='Postcode')),
                ('town_name', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Town Name')),
                ('town_name_kana', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Town Name Kana')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.municipality', verbose_name='Municipality')),
            ],
            options={
                'verbose_name': 'Postcode',
                'verbose_name_plural': 'Postcodes',
                'db_table': 'postcode',
                'ordering': ('postcode',),
                'constraints': [models.UniqueConstraint(fields=('postcode', 'municipality', 'town_name', 'town_name_kana'), name='unique_postcode_postcode_town_name')],
            },
            bases=(common.models.base.AuthorizedModelMixin, models.Model),
        ),
    ]
