# Generated by Django 6.0.7 on 2026-08-10 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日付')),
                ('type', models.CharField(choices=[('national', '国民の祝日'), ('company', '会社制定休日（夏季・年末年始等）'), ('legal', '法定休日'), ('non_legal', '法定外休日（所定休日）')], default='national', max_length=20, verbose_name='区分')),
                ('name', models.CharField(help_text='例: 元日、夏季休暇、創立記念日', max_length=100, verbose_name='休日名称')),
            ],
            options={
                'verbose_name': '祝日・休日',
                'verbose_name_plural': '祝日・休日',
                'db_table': 'holiday',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Prefecture Code')),
                ('name', models.CharField(max_length=100, verbose_name='Prefecture Name')),
            ],
            options={
                'verbose_name': 'Prefecture',
                'verbose_name_plural': 'Prefectures',
                'db_table': 'prefecture',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='WorkPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='勤務形態名')),
                ('start_time', models.TimeField(default='09:30', verbose_name='標準始業時刻')),
                ('end_time', models.TimeField(default='18:00', verbose_name='標準終業時刻')),
                ('lunch_break_start_time', models.TimeField(default='12:00', verbose_name='昼休開始時刻')),
                ('lunch_break_end_time', models.TimeField(default='13:00', verbose_name='昼休終了時刻')),
                ('break1_start_time', models.TimeField(default='18:00', verbose_name='休憩1開始時刻')),
                ('break1_end_time', models.TimeField(default='18:30', verbose_name='休憩1終了時刻')),
                ('break2_start_time', models.TimeField(default='20:00', verbose_name='休憩2開始時刻')),
                ('break2_end_time', models.TimeField(default='20:30', verbose_name='休憩2終了時刻')),
                ('break3_start_time', models.TimeField(default='22:30', verbose_name='休憩3開始時刻')),
                ('break3_end_time', models.TimeField(default='22:45', verbose_name='休憩3終了時刻')),
                ('break4_start_time', models.TimeField(default='03:00', verbose_name='休憩4開始時刻')),
                ('break4_end_time', models.TimeField(default='03:30', verbose_name='休憩4終了時刻')),
                ('break5_start_time', models.TimeField(default='09:00', verbose_name='休憩5開始時刻')),
                ('break5_end_time', models.TimeField(default='09:30', verbose_name='休憩5終了時刻')),
            ],
            options={
                'verbose_name': '勤務形態',
                'verbose_name_plural': '勤務形態',
                'db_table': 'work_pattern',
                'ordering': ('start_time',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_flag', models.BooleanField(default=True, verbose_name='Valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=150, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(max_length=150, verbose_name='Updated by')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Organization Code')),
                ('name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='common.organization', verbose_name='Parent Organization')),
                ('work_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.workpattern')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Municipality Code')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipality Name')),
                ('name_kana', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipality Name Kana')),
                ('prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.prefecture', verbose_name='Prefecture')),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
                'db_table': 'municipality',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_flag', models.BooleanField(default=True, verbose_name='Valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=150, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(max_length=150, verbose_name='Updated by')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email address')),
                ('manager_flag', models.BooleanField(default=False, verbose_name='Manager Flag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='Employee Number')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='common.organization', verbose_name='Belongs to')),
                ('work_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.workpattern')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=7, verbose_name='Postcode')),
                ('town_name', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Town Name')),
                ('town_name_kana', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Town Name Kana')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.municipality', verbose_name='Municipality')),
            ],
            options={
                'verbose_name': 'Postcode',
                'verbose_name_plural': 'Postcodes',
                'db_table': 'postcode',
                'ordering': ('postcode',),
                'constraints': [models.UniqueConstraint(fields=('postcode', 'municipality', 'town_name', 'town_name_kana'), name='unique_postcode_postcode_town_name')],
            },
        ),
    ]
