# Generated by Django 6.0.7 on 2026-09-04 11:26

import common.models.base
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_flag', models.BooleanField(default=True, verbose_name='Valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=150, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(max_length=150, verbose_name='Updated by')),
                ('version', models.IntegerField(default=0)),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('type', models.CharField(choices=[('national', 'National Holiday'), ('company', 'Company Holiday (Summer/New Year, etc.)')], default='national', max_length=20, verbose_name='Holiday Type')),
                ('name', models.CharField(help_text="e.g., New Year's Day, Summer Vacation, Foundation Day", max_length=100, verbose_name='Holiday Name')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'db_table': 'holiday',
                'ordering': ('date',),
            },
            bases=(common.models.base.MemberScopedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostcodeImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=7, verbose_name='Postcode')),
                ('municipality_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Municipality Code')),
                ('town_name', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Town Name')),
                ('town_name_kana', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Town Name Kana')),
            ],
            options={
                'db_table': 'tmp_postcode_import',
            },
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Prefecture Code')),
                ('name', models.CharField(max_length=100, verbose_name='Prefecture Name')),
            ],
            options={
                'verbose_name': 'Prefecture',
                'verbose_name_plural': 'Prefectures',
                'db_table': 'prefecture',
                'ordering': ('code',),
            },
            bases=(common.models.base.MemberScopedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TransportationCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_cd', models.IntegerField(unique=True, verbose_name='事業者コード')),
                ('rr_cd', models.IntegerField(verbose_name='鉄道コード')),
                ('company_name', models.CharField(max_length=80, verbose_name='事業者名')),
                ('company_name_k', models.CharField(blank=True, max_length=80, null=True, verbose_name='事業者名カナ')),
                ('company_name_h', models.CharField(blank=True, max_length=80, null=True, verbose_name='事業者名正式表記')),
                ('company_name_r', models.CharField(blank=True, max_length=80, null=True, verbose_name='事業者名略称')),
                ('company_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='事業者URL')),
                ('company_type', models.IntegerField(blank=True, choices=[(0, 'その他'), (1, 'JR'), (2, '大手私鉄'), (3, '準大手私鉄')], null=True, verbose_name='事業者種別')),
                ('e_status', models.IntegerField(blank=True, choices=[(0, '運用中'), (1, '運用前'), (2, '廃止')], null=True, verbose_name='運用状況')),
            ],
            options={
                'verbose_name': '鉄道事業者',
                'verbose_name_plural': '鉄道事業者',
                'db_table': 'transportation_company',
            },
            bases=(common.models.base.MemberScopedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_flag', models.BooleanField(default=True, verbose_name='Valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=150, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(max_length=150, verbose_name='Updated by')),
                ('version', models.IntegerField(default=0)),
                ('no', models.IntegerField(unique=True, verbose_name='Work Pattern Code')),
                ('name', models.CharField(max_length=100, verbose_name='Work Pattern Name')),
                ('start_time', models.TimeField(blank=True, default='09:30', null=True, verbose_name='Standard Start Time')),
                ('end_time', models.TimeField(blank=True, default='18:00', null=True, verbose_name='Standard End Time')),
                ('standard_work_time', models.TimeField(blank=True, default='07:30', null=True, verbose_name='Standard Working Time')),
                ('half_day_time', models.TimeField(blank=True, default='12:30', null=True, verbose_name='Half Day Time')),
                ('lunch_break_start_time', models.TimeField(blank=True, default='12:00', null=True, verbose_name='Lunch Break Start Time')),
                ('lunch_break_end_time', models.TimeField(blank=True, default='13:00', null=True, verbose_name='Lunch Break End Time')),
                ('break1_start_time', models.TimeField(blank=True, default='18:00', null=True, verbose_name='Break 1 Start Time')),
                ('break1_end_time', models.TimeField(blank=True, default='18:30', null=True, verbose_name='Break 1 End Time')),
                ('break2_start_time', models.TimeField(blank=True, default='20:00', null=True, verbose_name='Break 2 Start Time')),
                ('break2_end_time', models.TimeField(blank=True, default='20:30', null=True, verbose_name='Break 2 End Time')),
                ('break3_start_time', models.TimeField(blank=True, default='22:30', null=True, verbose_name='Break 3 Start Time')),
                ('break3_end_time', models.TimeField(blank=True, default='22:45', null=True, verbose_name='Break 3 End Time')),
                ('break4_start_time', models.TimeField(blank=True, default='03:00', null=True, verbose_name='Break 4 Start Time')),
                ('break4_end_time', models.TimeField(blank=True, default='03:30', null=True, verbose_name='Break 4 End Time')),
                ('break5_start_time', models.TimeField(blank=True, default='09:00', null=True, verbose_name='Break 5 Start Time')),
                ('break5_end_time', models.TimeField(blank=True, default='09:30', null=True, verbose_name='Break 5 End Time')),
            ],
            options={
                'verbose_name': 'Work Pattern',
                'verbose_name_plural': 'Work Patterns',
                'db_table': 'work_pattern',
                'ordering': ('no',),
            },
            bases=(common.models.base.MemberScopedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_flag', models.BooleanField(default=True, verbose_name='Valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=150, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(max_length=150, verbose_name='Updated by')),
                ('version', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Organization Code')),
                ('name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='common.organization', verbose_name='Parent Organization')),
                ('work_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.workpattern', verbose_name='Work Pattern')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organization',
            },
            bases=(common.models.base.MemberScopedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Municipality Code')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipality Name')),
                ('name_kana', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipality Name Kana')),
                ('prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.prefecture', verbose_name='Prefecture')),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
                'db_table': 'municipality',
                'ordering': ('code',),
            },
            bases=(common.models.base.MemberScopedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TransportationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_cd', models.IntegerField(unique=True, verbose_name='路線コード')),
                ('line_name', models.CharField(max_length=80, verbose_name='路線名')),
                ('line_name_k', models.CharField(blank=True, max_length=80, null=True, verbose_name='路線名カナ')),
                ('line_name_h', models.CharField(blank=True, max_length=80, null=True, verbose_name='路線名正式表記')),
                ('line_type', models.IntegerField(blank=True, choices=[(0, 'その他'), (1, '新幹線'), (2, '一般'), (3, '地下鉄'), (4, '市電・路面電車'), (5, 'モノレール・新交通')], null=True, verbose_name='路線区分')),
                ('e_status', models.IntegerField(blank=True, choices=[(0, '運用中'), (1, '運用前'), (2, '廃止')], null=True, verbose_name='運用状況')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='common.transportationcompany', verbose_name='事業者')),
            ],
            options={
                'verbose_name': '路線',
                'verbose_name_plural': '路線',
                'db_table': 'transportation_line',
            },
            bases=(common.models.base.MemberScopedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TransportationStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_cd', models.IntegerField(unique=True, verbose_name='駅コード')),
                ('station_g_cd', models.IntegerField(blank=True, null=True, verbose_name='駅グループコード')),
                ('station_name', models.CharField(max_length=80, verbose_name='駅名')),
                ('station_name_k', models.CharField(blank=True, max_length=80, null=True, verbose_name='駅名カナ')),
                ('station_name_r', models.CharField(blank=True, max_length=200, null=True, verbose_name='駅名ローマ字')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='住所')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='経度')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('open_ymd', models.DateField(blank=True, null=True, verbose_name='開業日')),
                ('close_ymd', models.DateField(blank=True, null=True, verbose_name='廃止日')),
                ('e_status', models.IntegerField(blank=True, choices=[(0, '運用中'), (1, '運用前'), (2, '廃止')], null=True, verbose_name='運用状況')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='common.transportationline', verbose_name='路線')),
            ],
            options={
                'verbose_name': '駅',
                'verbose_name_plural': '駅',
                'db_table': 'transportation_station',
            },
            bases=(common.models.base.MemberScopedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_flag', models.BooleanField(default=True, verbose_name='Valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=150, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(max_length=150, verbose_name='Updated by')),
                ('version', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='Employee Number')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='common.organization', verbose_name='Belongs to')),
                ('work_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.workpattern', verbose_name='Work Pattern')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'member',
            },
            bases=(common.models.base.RowScopedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=7, verbose_name='Postcode')),
                ('town_name', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Town Name')),
                ('town_name_kana', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Town Name Kana')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.municipality', verbose_name='Municipality')),
            ],
            options={
                'verbose_name': 'Postcode',
                'verbose_name_plural': 'Postcodes',
                'db_table': 'postcode',
                'ordering': ('postcode',),
                'constraints': [models.UniqueConstraint(fields=('postcode', 'municipality', 'town_name', 'town_name_kana'), name='unique_postcode_postcode_town_name')],
            },
            bases=(common.models.base.MemberScopedModelMixin, models.Model),
        ),
    ]
