# Generated by Django 6.0.7 on 2026-08-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='version',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='version',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
