# Generated by Django 6.0.7 on 2026-09-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name='Join Date'),
        ),
        migrations.AddField(
            model_name='member',
            name='yearly_paid_leave_days',
            field=models.IntegerField(default=0, verbose_name='Yearly Paid Leave Days'),
        ),
    ]
