# Generated by Django 6.0.7 on 2026-08-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpattern',
            name='standard_work_time',
            field=models.TimeField(blank=True, default='07:30', null=True, verbose_name='Standard Working Time'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='break1_end_time',
            field=models.TimeField(blank=True, default='18:30', null=True, verbose_name='Break 1 End Time'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='break1_start_time',
            field=models.TimeField(blank=True, default='18:00', null=True, verbose_name='Break 1 Start Time'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='break2_end_time',
            field=models.TimeField(blank=True, default='20:30', null=True, verbose_name='Break 2 End Time'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='break2_start_time',
            field=models.TimeField(blank=True, default='20:00', null=True, verbose_name='Break 2 Start Time'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='break3_end_time',
            field=models.TimeField(blank=True, default='22:45', null=True, verbose_name='Break 3 End Time'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='break3_start_time',
            field=models.TimeField(blank=True, default='22:30', null=True, verbose_name='Break 3 Start Time'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='break4_end_time',
            field=models.TimeField(blank=True, default='03:30', null=True, verbose_name='Break 4 End Time'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='break4_start_time',
            field=models.TimeField(blank=True, default='03:00', null=True, verbose_name='Break 4 Start Time'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='break5_end_time',
            field=models.TimeField(blank=True, default='09:30', null=True, verbose_name='Break 5 End Time'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='break5_start_time',
            field=models.TimeField(blank=True, default='09:00', null=True, verbose_name='Break 5 Start Time'),
        ),
    ]
