# Generated by Django 6.0.7 on 2026-08-06 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_flag', models.BooleanField(default=True, verbose_name='Valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=150, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(max_length=150, verbose_name='Updated by')),
                ('municipality_code', models.CharField(max_length=10, verbose_name='Municipality Code')),
                ('municipality_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipality Name')),
                ('municipality_name_kana', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipality Name Kana')),
                ('prefecture_name', models.CharField(max_length=100, verbose_name='Prefecture Name')),
                ('prefecture_name_kana', models.CharField(max_length=100, verbose_name='Prefecture Name Kana')),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
                'ordering': ['municipality_code'],
                'constraints': [models.UniqueConstraint(fields=('municipality_code',), name='unique_municipality_code')],
            },
        ),
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_flag', models.BooleanField(default=True, verbose_name='Valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=150, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(max_length=150, verbose_name='Updated by')),
                ('postcode', models.CharField(max_length=7, verbose_name='Postcode')),
                ('town_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Town Name')),
                ('town_name_kana', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Town Name Kana')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.municipality', verbose_name='Municipality')),
            ],
            options={
                'verbose_name': 'Postcode',
                'verbose_name_plural': 'Postcodes',
                'ordering': ['postcode'],
                'constraints': [models.UniqueConstraint(fields=('postcode', 'municipality', 'town_name', 'town_name_kana'), name='unique_postcode_postcode_town_name')],
            },
        ),
    ]
