# Generated by Django 6.0.7 on 2026-08-06 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_municipality_postcode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='municipality',
            table='municipality',
        ),
        migrations.AlterModelTable(
            name='postcode',
            table='postcode',
        ),
    ]
