# Generated by Django 6.0.7 on 2026-08-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_workpattern_standard_work_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpattern',
            name='half_day_time',
            field=models.TimeField(blank=True, default='12:30', null=True, verbose_name='Half Day Time'),
        ),
    ]
