# Generated by Django 6.0.7 on 2026-09-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_member_join_date_member_yearly_paid_leave_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='yearly_paid_leave_days',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Yearly Paid Leave Days'),
        ),
    ]
