# Generated by Django 6.0.7 on 2026-08-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_workpattern_half_day_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpattern',
            name='end_time',
            field=models.TimeField(blank=True, default='18:00', null=True, verbose_name='Standard End Time'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='lunch_break_end_time',
            field=models.TimeField(blank=True, default='13:00', null=True, verbose_name='Lunch Break End Time'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='lunch_break_start_time',
            field=models.TimeField(blank=True, default='12:00', null=True, verbose_name='Lunch Break Start Time'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='start_time',
            field=models.TimeField(blank=True, default='09:30', null=True, verbose_name='Standard Start Time'),
        ),
    ]
