# Generated by Django 6.0.7 on 2026-09-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_member_yearly_paid_leave_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='yearly_paid_leave_days',
        ),
        migrations.AddField(
            model_name='member',
            name='paid_leave_available',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Available Paid Leave'),
        ),
    ]
