# Generated by Django 6.0.7 on 2026-08-06 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_municipality_table_alter_postcode_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='Prefecture Code')),
                ('name', models.CharField(max_length=100, verbose_name='Prefecture Name')),
            ],
            options={
                'verbose_name': 'Prefecture',
                'verbose_name_plural': 'Prefectures',
                'db_table': 'prefecture',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ['code'], 'verbose_name': 'Municipality', 'verbose_name_plural': 'Municipalities'},
        ),
        migrations.RemoveConstraint(
            model_name='municipality',
            name='unique_municipality_code',
        ),
        migrations.RenameField(
            model_name='municipality',
            old_name='municipality_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='municipality',
            old_name='municipality_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='municipality',
            old_name='municipality_name_kana',
            new_name='name_kana',
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.municipality', verbose_name='Municipality'),
        ),
        migrations.AddConstraint(
            model_name='prefecture',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_prefecture_code'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='prefecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.prefecture', verbose_name='Prefecture'),
        ),
        migrations.AddConstraint(
            model_name='municipality',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_municipality_code'),
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='prefecture_name',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='prefecture_name_kana',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='valid_flag',
        ),
    ]
