# Generated by Django 6.0.7 on 2026-09-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_member_yearly_paid_leave_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='paid_leave_available',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Available Paid Leave'),
        ),
    ]
