# Generated by Django 6.0.7 on 2026-08-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_prefecture_alter_municipality_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='code',
            field=models.CharField(max_length=5, verbose_name='Municipality Code'),
        ),
    ]
