# Generated by Django 6.0.7 on 2026-08-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_municipality_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ('code',), 'verbose_name': 'Municipality', 'verbose_name_plural': 'Municipalities'},
        ),
        migrations.AlterModelOptions(
            name='postcode',
            options={'ordering': ('postcode',), 'verbose_name': 'Postcode', 'verbose_name_plural': 'Postcodes'},
        ),
        migrations.AlterModelOptions(
            name='prefecture',
            options={'ordering': ('code',), 'verbose_name': 'Prefecture', 'verbose_name_plural': 'Prefectures'},
        ),
        migrations.RemoveConstraint(
            model_name='municipality',
            name='unique_municipality_code',
        ),
        migrations.RemoveConstraint(
            model_name='prefecture',
            name='unique_prefecture_code',
        ),
        migrations.AlterField(
            model_name='municipality',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Municipality Code'),
        ),
        migrations.AlterField(
            model_name='prefecture',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='Prefecture Code'),
        ),
    ]
