# Generated by Django 6.0.7 on 2026-09-08 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_member_paid_leave_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='paid_leave_available',
        ),
    ]
