# Generated by Django 6.0.7 on 2026-08-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_municipality_options_alter_postcode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcode',
            name='town_name',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Town Name'),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='town_name_kana',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Town Name Kana'),
        ),
    ]
