# Generated by Django 6.0.7 on 2026-08-09 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日付')),
                ('type', models.CharField(choices=[('national', '国民の祝日'), ('company', '会社制定休日（夏季・年末年始等）'), ('legal', '法定休日'), ('non_legal', '法定外休日（所定休日）')], default='national', max_length=20, verbose_name='区分')),
                ('name', models.CharField(help_text='例: 元日、夏季休暇、創立記念日', max_length=100, verbose_name='休日名称')),
            ],
            options={
                'verbose_name': '祝日・休日',
                'verbose_name_plural': '祝日・休日',
                'db_table': 'holiday',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='WorkPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='勤務形態名')),
                ('start_time', models.TimeField(default='09:30', verbose_name='標準始業時刻')),
                ('end_time', models.TimeField(default='18:00', verbose_name='標準終業時刻')),
                ('lunch_break_start_time', models.TimeField(default='12:00', verbose_name='標準休憩開始時刻')),
                ('lunch_break_end_time', models.TimeField(default='13:00', verbose_name='標準休憩終了時刻')),
                ('break1_start_time', models.TimeField(default='18:00', verbose_name='標準休憩開始時刻')),
                ('break1_end_time', models.TimeField(default='18:30', verbose_name='標準休憩終了時刻')),
                ('break2_start_time', models.TimeField(default='20:00', verbose_name='標準休憩開始時刻')),
                ('break2_end_time', models.TimeField(default='20:30', verbose_name='標準休憩終了時刻')),
                ('break3_start_time', models.TimeField(default='22:30', verbose_name='標準休憩開始時刻')),
                ('break3_end_time', models.TimeField(default='22:45', verbose_name='標準休憩終了時刻')),
                ('break4_start_time', models.TimeField(default='03:00', verbose_name='標準休憩開始時刻')),
                ('break4_end_time', models.TimeField(default='03:30', verbose_name='標準休憩終了時刻')),
                ('break5_start_time', models.TimeField(default='09:00', verbose_name='標準休憩開始時刻')),
                ('break5_end_time', models.TimeField(default='09:30', verbose_name='標準休憩終了時刻')),
            ],
            options={
                'verbose_name': '勤務形態',
                'verbose_name_plural': '勤務形態一覧',
                'db_table': 'work_pattern',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='対象日')),
                ('date_type', models.CharField(choices=[(0, '出勤'), (1, '欠勤'), (2, '午前半休'), (3, '午後半休'), (4, '有休'), (5, '特別休暇'), (6, '休日')], default=0, max_length=20, verbose_name='勤務状態')),
                ('approve_status', models.CharField(choices=[(0, '入力中'), (1, '申請済'), (2, '承認済'), (3, '却下'), (4, '確定済')], default=0, max_length=20, verbose_name='処理状態')),
                ('reject_reason', models.CharField(blank=True, max_length=255, verbose_name='却下理由')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='備考')),
                ('clock_in_time', models.DateTimeField(blank=True, null=True, verbose_name='出勤日時')),
                ('clock_out_time', models.DateTimeField(blank=True, null=True, verbose_name='退勤日時')),
                ('has_lunch_break', models.BooleanField(default=True, verbose_name='ランチ休憩有無')),
                ('has_break1', models.BooleanField(default=True, verbose_name='休憩1有無')),
                ('has_break2', models.BooleanField(default=True, verbose_name='休憩2有無')),
                ('has_break3', models.BooleanField(default=True, verbose_name='休憩3有無')),
                ('has_break4', models.BooleanField(default=True, verbose_name='休憩4有無')),
                ('has_break5', models.BooleanField(default=True, verbose_name='休憩5有無')),
                ('other_break_minutes', models.PositiveIntegerField(default=0, verbose_name='その他休憩時間（分）')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance_records', to='common.member', verbose_name='社員')),
                ('work_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kintai.workpattern', verbose_name='勤務形態')),
            ],
            options={
                'verbose_name': '日次勤怠',
                'verbose_name_plural': '日次勤怠一覧',
                'db_table': 'attendance_record',
                'ordering': ('-date', 'member'),
                'unique_together': {('member', 'date')},
            },
        ),
    ]
