# Generated by Django 6.0.7 on 2026-08-21 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_alter_workpattern_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_flag', models.BooleanField(default=True, verbose_name='Valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=150, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(max_length=150, verbose_name='Updated by')),
                ('month', models.DateField(verbose_name='Month')),
                ('approve_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Applied'), (2, 'Approved'), (3, 'Rejected'), (4, 'Finalized')], default=0, verbose_name='Approve Status')),
                ('actual_work_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Actual Working Time')),
                ('overtime_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Overtime')),
                ('night_work_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Night Working Time')),
                ('worked_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Days Worked')),
                ('paid_leave_days', models.FloatField(blank=True, null=True, verbose_name='Paid Leave Days')),
                ('standard_working_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Standard Working Days')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Note')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance_records', to='common.member', verbose_name='Member')),
                ('work_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.workpattern', verbose_name='Work Pattern')),
            ],
            options={
                'verbose_name': 'Monthly Attendance',
                'verbose_name_plural': 'Monthly Attendances',
                'db_table': 'attendance_monthly',
                'ordering': ('-month', 'member'),
                'unique_together': {('member', 'month')},
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Day')),
                ('date_type', models.IntegerField(choices=[(0, 'Work Day'), (1, 'Scheduled Day Off'), (2, 'Statutory Day Off'), (3, 'National Holiday'), (4, 'Transfer Holiday')], default=0, verbose_name='Date Type')),
                ('date_status', models.IntegerField(blank=True, choices=[(0, 'Present'), (1, 'Absent'), (2, 'Morning Half-Day Leave'), (3, 'Afternoon Half-Day Leave'), (4, 'Paid Leave'), (5, 'Special Paid Leave'), (6, 'Substitute Holiday'), (7, 'Compensatory Holiday'), (8, 'SP5')], default=0, null=True, verbose_name='Date Status')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Note')),
                ('clock_in_time', models.DateTimeField(blank=True, null=True, verbose_name='Clock In')),
                ('clock_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Clock Out')),
                ('has_lunch_break', models.BooleanField(default=True, verbose_name='Lunch Break')),
                ('has_break1', models.BooleanField(default=True, verbose_name='Break 1')),
                ('has_break2', models.BooleanField(default=True, verbose_name='Break 2')),
                ('has_break3', models.BooleanField(default=True, verbose_name='Break 3')),
                ('has_break4', models.BooleanField(default=True, verbose_name='Break 4')),
                ('has_break5', models.BooleanField(default=True, verbose_name='Break 5')),
                ('day_absence', models.TimeField(blank=True, null=True, verbose_name='Day Absence')),
                ('night_absence', models.TimeField(blank=True, null=True, verbose_name='Night Absence')),
                ('actual_work_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Actual Working Time')),
                ('overtime_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Overtime')),
                ('night_work_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Night Working Time')),
                ('late_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Late')),
                ('early_leave_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Early Leave')),
                ('work_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.workpattern', verbose_name='Work Pattern')),
                ('monthly_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='kintai.monthlyattendance', verbose_name='Monthly Attendance')),
            ],
            options={
                'verbose_name': 'Daily Attendance',
                'verbose_name_plural': 'Daily Attendances',
                'db_table': 'attendance_daily',
                'ordering': ('monthly_attendance', 'day'),
                'unique_together': {('monthly_attendance', 'day')},
            },
        ),
    ]
