# Generated by Django 6.0.7 on 2026-08-12 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_flag', models.BooleanField(default=True, verbose_name='Valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=150, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(max_length=150, verbose_name='Updated by')),
                ('date', models.DateField(verbose_name='対象月')),
                ('approve_status', models.CharField(choices=[(0, '入力中'), (1, '申請済'), (2, '承認済'), (3, '却下'), (4, '確定済')], default=0, max_length=2, verbose_name='状態')),
                ('actual_work_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='実労働時間')),
                ('overtime_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='残業時間')),
                ('night_work_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='深夜労働時間')),
                ('worked_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='出勤日数')),
                ('paid_leave_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='有休日数')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance_records', to='common.member', verbose_name='社員')),
                ('work_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.workpattern', verbose_name='勤務形態')),
            ],
            options={
                'verbose_name': '月次勤怠',
                'verbose_name_plural': '月次勤怠一覧',
                'db_table': 'attendance_monthly',
                'ordering': ('-date', 'member'),
                'unique_together': {('member', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='対象日')),
                ('date_type', models.CharField(choices=[(0, '出勤'), (1, '欠勤'), (2, '午前半休'), (3, '午後半休'), (4, '有休'), (5, '特別休暇'), (6, '休日')], default=0, max_length=20, verbose_name='勤務状態')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('clock_in_time', models.DateTimeField(blank=True, null=True, verbose_name='出勤日時')),
                ('clock_out_time', models.DateTimeField(blank=True, null=True, verbose_name='退勤日時')),
                ('has_lunch_break', models.BooleanField(blank=True, null=True, verbose_name='ランチ休憩有無')),
                ('has_break1', models.BooleanField(blank=True, null=True, verbose_name='休憩1有無')),
                ('has_break2', models.BooleanField(blank=True, null=True, verbose_name='休憩2有無')),
                ('has_break3', models.BooleanField(blank=True, null=True, verbose_name='休憩3有無')),
                ('has_break4', models.BooleanField(blank=True, null=True, verbose_name='休憩4有無')),
                ('has_break5', models.BooleanField(blank=True, null=True, verbose_name='休憩5有無')),
                ('other_break_minutes', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='その他休憩時間（分）')),
                ('work_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.workpattern', verbose_name='勤務形態')),
                ('monthly_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='kintai.monthlyattendance', verbose_name='月次勤怠')),
            ],
            options={
                'verbose_name': '日次勤怠',
                'verbose_name_plural': '日次勤怠一覧',
                'db_table': 'attendance_daily',
                'ordering': ('-date', 'monthly_attendance__member'),
                'unique_together': {('monthly_attendance', 'date')},
            },
        ),
    ]
