# Generated by Django 6.0.7 on 2026-09-07 23:05

import common.models.base
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_member_paid_leave_available'),
        ('kintai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('acquired_days', models.FloatField()),
                ('remaining_days', models.FloatField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.member')),
            ],
            options={
                'verbose_name': 'Paid Leave',
                'db_table': 'paid_leave',
                'unique_together': {('member', 'year')},
            },
            bases=(common.models.base.RowScopedModelMixin, models.Model),
        ),
    ]
