# Generated by Django 6.0.7 on 2026-08-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyattendance',
            name='paid_leave_days',
            field=models.PositiveIntegerField(default=0, verbose_name='有給休暇日数'),
        ),
        migrations.AddField(
            model_name='monthlyattendance',
            name='worked_days',
            field=models.PositiveIntegerField(default=0, verbose_name='出勤日数'),
        ),
    ]
