# Generated by Django 6.0.7 on 2026-08-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyattendance',
            name='absent_days',
            field=models.FloatField(blank=True, null=True, verbose_name='Absent Days'),
        ),
        migrations.AddField(
            model_name='monthlyattendance',
            name='early_leave_days',
            field=models.FloatField(blank=True, null=True, verbose_name='Early Leave Days'),
        ),
        migrations.AddField(
            model_name='monthlyattendance',
            name='late_days',
            field=models.FloatField(blank=True, null=True, verbose_name='Late Days'),
        ),
        migrations.AddField(
            model_name='monthlyattendance',
            name='total_absence_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Absence Time'),
        ),
    ]
