# Generated by Django 6.0.7 on 2026-08-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyattendance',
            options={'ordering': ('date',), 'verbose_name': '日次勤怠', 'verbose_name_plural': '日次勤怠一覧'},
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='clock_in_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出勤'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='clock_out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退勤'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='date_type',
            field=models.IntegerField(choices=[(0, '出勤'), (1, '欠勤'), (2, '午前休'), (3, '午後休'), (4, '有休'), (5, '特別休'), (6, '休日'), (7, '祝日'), (8, '振替休'), (9, '代休')], default=0, verbose_name='勤務状態'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='has_break1',
            field=models.BooleanField(blank=True, null=True, verbose_name='休憩1'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='has_break2',
            field=models.BooleanField(blank=True, null=True, verbose_name='休憩2'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='has_break3',
            field=models.BooleanField(blank=True, null=True, verbose_name='休憩3'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='has_break4',
            field=models.BooleanField(blank=True, null=True, verbose_name='休憩4'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='has_break5',
            field=models.BooleanField(blank=True, null=True, verbose_name='休憩5'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='has_lunch_break',
            field=models.BooleanField(blank=True, null=True, verbose_name='昼休憩'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='other_break_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='不在'),
        ),
    ]
