# Generated by Django 6.0.7 on 2026-09-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyattendance',
            name='day_absence',
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='night_absence',
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='night_work_minutes',
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='overtime_minutes',
        ),
        migrations.RemoveField(
            model_name='monthlyattendance',
            name='night_work_minutes',
        ),
        migrations.RemoveField(
            model_name='monthlyattendance',
            name='overtime_minutes',
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='absence_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Absence End'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='absence_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Absence Start'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='holiday_135',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Holiday 1.35'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='holiday_160',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Holiday 1.60'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='night_time_025',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Night Overtime 0.25'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='off_day_125',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Off Day 1.25'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='off_day_150',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Off Day 1.50'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='overtime_125',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Overtime 1.25'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='overtime_150',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Overtime 1.50'),
        ),
        migrations.AddField(
            model_name='monthlyattendance',
            name='holiday_135',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Holiday 1.35'),
        ),
        migrations.AddField(
            model_name='monthlyattendance',
            name='holiday_160',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Holiday 1.60'),
        ),
        migrations.AddField(
            model_name='monthlyattendance',
            name='night_time_025',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Night Overtime 0.25'),
        ),
        migrations.AddField(
            model_name='monthlyattendance',
            name='off_day_125',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Off Day 1.25'),
        ),
        migrations.AddField(
            model_name='monthlyattendance',
            name='off_day_150',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Off Day 1.50'),
        ),
        migrations.AddField(
            model_name='monthlyattendance',
            name='overtime_125',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Overtime 1.25'),
        ),
        migrations.AddField(
            model_name='monthlyattendance',
            name='overtime_150',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Overtime 1.50'),
        ),
    ]
