# Generated by Django 6.0.7 on 2026-08-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyattendance',
            name='approve_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Applied'), (2, 'Approved'), (3, 'Rejected'), (4, 'Finalized')], default=0, verbose_name='Approve Status'),
        ),
    ]
