# Generated by Django 6.0.7 on 2026-08-20 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyattendance',
            options={'ordering': ('monthly_attendance', 'day'), 'verbose_name': 'Daily Attendance', 'verbose_name_plural': 'Daily Attendances'},
        ),
    ]
