# Generated by Django 6.0.7 on 2026-08-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0002_monthlyattendance_absent_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyattendance',
            name='absent_days',
        ),
        migrations.AddField(
            model_name='monthlyattendance',
            name='absence_days',
            field=models.FloatField(blank=True, null=True, verbose_name='Absence Days'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='date_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Present'), (1, 'Absence'), (2, 'Morning Half-Day Leave'), (3, 'Afternoon Half-Day Leave'), (4, 'Paid Leave'), (5, 'Special Paid Leave'), (6, 'Substitute Holiday'), (7, 'Compensatory Holiday'), (8, 'SP5')], default=0, null=True, verbose_name='Date Status'),
        ),
    ]
