# Generated by Django 6.0.7 on 2026-08-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0002_monthlyattendance_paid_leave_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyattendance',
            name='actual_work_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='実労働時間（分）'),
        ),
        migrations.AlterField(
            model_name='monthlyattendance',
            name='date',
            field=models.DateField(verbose_name='対象月'),
        ),
        migrations.AlterField(
            model_name='monthlyattendance',
            name='night_work_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='深夜労働時間（分）'),
        ),
        migrations.AlterField(
            model_name='monthlyattendance',
            name='overtime_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='残業時間（分）'),
        ),
        migrations.AlterField(
            model_name='monthlyattendance',
            name='paid_leave_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='有給休暇日数'),
        ),
        migrations.AlterField(
            model_name='monthlyattendance',
            name='worked_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='出勤日数'),
        ),
    ]
