# Generated by Django 6.0.7 on 2026-08-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0002_alter_monthlyattendance_approve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='date_status',
            field=models.IntegerField(choices=[(0, 'Day Off'), (1, 'Present'), (2, 'Absent'), (3, 'Morning Half-Day Leave'), (4, 'Afternoon Half-Day Leave'), (5, 'Paid Leave'), (6, 'Special Paid Leave'), (7, 'Substitute Holiday'), (8, 'Compensatory Holiday'), (9, 'SP5')], default=1, verbose_name='Date Status'),
        ),
    ]
