# Generated by Django 6.0.7 on 2026-09-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0002_remove_dailyattendance_day_absence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyattendance',
            name='total_absence_minutes',
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='night_time_025',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Night Work 0.25'),
        ),
    ]
