# Generated by Django 6.0.7 on 2026-08-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0002_alter_dailyattendance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='actual_work_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Actual Working Time'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='night_work_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Night Working Time'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='overtime_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Overtime'),
        ),
    ]
