# Generated by Django 6.0.7 on 2026-09-08 00:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_member_paid_leave_available'),
        ('kintai', '0002_paidleave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paidleave',
            options={'verbose_name': 'Paid Leave', 'verbose_name_plural': 'Paid Leaves'},
        ),
        migrations.RenameField(
            model_name='monthlyattendance',
            old_name='paid_leave_days',
            new_name='taken_paid_leaves',
        ),
        migrations.AddField(
            model_name='paidleave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidleave',
            name='created_by',
            field=models.CharField(default='admin', max_length=150, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidleave',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='paidleave',
            name='updated_by',
            field=models.CharField(default='admin', max_length=150, verbose_name='Updated by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidleave',
            name='valid_flag',
            field=models.BooleanField(default=True, verbose_name='Valid'),
        ),
        migrations.AddField(
            model_name='paidleave',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paidleave',
            name='acquired_days',
            field=models.FloatField(default=0, verbose_name='Acquired Days'),
        ),
        migrations.AlterField(
            model_name='paidleave',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_leaves', to='common.member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='paidleave',
            name='remaining_days',
            field=models.FloatField(default=0, verbose_name='Remaining Days'),
        ),
        migrations.AlterField(
            model_name='paidleave',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
    ]
