# Generated by Django 6.0.7 on 2026-08-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0002_alter_dailyattendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='date_status',
            field=models.IntegerField(choices=[(0, '出勤'), (1, '遅刻'), (2, '早退'), (3, '欠勤'), (4, '遅刻・早退'), (5, '午前休'), (6, '午後休'), (7, '有休'), (8, '特別休'), (9, '振休'), (10, '代休'), (11, 'SP5')], default=0, verbose_name='勤怠状況'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='date_type',
            field=models.IntegerField(choices=[(0, '出勤日'), (1, '所定休'), (2, '法定休'), (3, '祝日'), (4, '振替休日')], default=0, verbose_name='勤務区分'),
        ),
    ]
