# Generated by Django 6.0.7 on 2026-08-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0003_dailyattendance_date_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='date_status',
            field=models.IntegerField(choices=[(0, '出勤'), (1, '休み'), (2, '遅刻'), (4, '早退'), (5, '欠勤'), (6, '遅刻・早退'), (7, '午前休'), (8, '午後休'), (9, '有休'), (10, '特別休'), (11, '振休'), (12, '代休'), (13, 'SP5')], default=0, verbose_name='勤怠状況'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='has_break1',
            field=models.BooleanField(default=True, verbose_name='休憩1'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='has_break2',
            field=models.BooleanField(default=True, verbose_name='休憩2'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='has_break3',
            field=models.BooleanField(default=True, verbose_name='休憩3'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='has_break4',
            field=models.BooleanField(default=True, verbose_name='休憩4'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='has_break5',
            field=models.BooleanField(default=True, verbose_name='休憩5'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='has_lunch_break',
            field=models.BooleanField(default=True, verbose_name='昼休憩'),
        ),
    ]
