# Generated by Django 6.0.7 on 2026-08-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0003_alter_dailyattendance_date_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='substitute_day',
            field=models.DateField(blank=True, null=True, verbose_name='Substitute Day'),
        ),
    ]
