# Generated by Django 6.0.7 on 2026-08-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0003_alter_monthlyattendance_actual_work_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='has_break1',
            field=models.BooleanField(blank=True, null=True, verbose_name='休憩1有無'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='has_break2',
            field=models.BooleanField(blank=True, null=True, verbose_name='休憩2有無'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='has_break3',
            field=models.BooleanField(blank=True, null=True, verbose_name='休憩3有無'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='has_break4',
            field=models.BooleanField(blank=True, null=True, verbose_name='休憩4有無'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='has_break5',
            field=models.BooleanField(blank=True, null=True, verbose_name='休憩5有無'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='has_lunch_break',
            field=models.BooleanField(blank=True, null=True, verbose_name='ランチ休憩有無'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='other_break_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='その他休憩時間（分）'),
        ),
        migrations.AlterField(
            model_name='monthlyattendance',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='備考'),
        ),
    ]
