# Generated by Django 6.0.7 on 2026-08-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0003_dailyattendance_actual_work_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='early_leave_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Early Leave'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='late_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Late'),
        ),
    ]
