# Generated by Django 6.0.7 on 2026-08-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0004_alter_dailyattendance_has_break1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='備考'),
        ),
    ]
