# Generated by Django 6.0.7 on 2026-08-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0004_alter_dailyattendance_date_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='other_break_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='一時不在(分)'),
        ),
    ]
