# Generated by Django 6.0.7 on 2026-08-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0001_initial_squashed_0005_alter_member_created_by_alter_member_updated_by'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
    ]
