# Generated by Django 6.0.7 on 2026-08-04 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0006_alter_member_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='valid_flag',
            field=models.BooleanField(default=True, verbose_name='Valid'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=150, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(max_length=150, verbose_name='Updated by')),
                ('valid_flag', models.BooleanField(default=True, verbose_name='Valid')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Organization Code')),
                ('name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='kintai.organization', verbose_name='Parent Organization')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organization',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='kintai.organization', verbose_name='Organization'),
        ),
    ]
