# Generated by Django 6.0.7 on 2026-08-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0007_member_valid_flag_organization_member_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Organization Name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='Organization Name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_zh_hans',
            field=models.CharField(max_length=255, null=True, verbose_name='Organization Name'),
        ),
    ]
