# Generated by Django 6.0.7 on 2026-08-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0008_organization_name_en_organization_name_ja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name_ja',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name_zh_hans',
        ),
    ]
